//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.18 at 06:29:50 PM MSK 
//


package com.skat.smev.gisgmp.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExportQuittancesKindType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExportQuittancesKindType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="QUITTANCE"/>
 *     &lt;enumeration value="ALLQUITTANCE"/>
 *     &lt;enumeration value="QUITTANCEMAINCHARGE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ExportQuittancesKindType", namespace = "http://roskazna.ru/gisgmp/xsd/SearchConditions/2.0.1")
@XmlEnum
public enum ExportQuittancesKindType {

    QUITTANCE,
    ALLQUITTANCE,
    QUITTANCEMAINCHARGE;

    public String value() {
        return name();
    }

    public static ExportQuittancesKindType fromValue(String v) {
        return valueOf(v);
    }

}
