//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.18 at 06:29:50 PM MSK 
//


package com.skat.smev.gisgmp.model;

import com.skat.smev.gisgmp.domain.*;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://roskazna.ru/gisgmp/xsd/Common/2.0.1}ExportRequestType">
 *       &lt;sequence>
 *         &lt;element name="EsiaUserInfo" type="{http://roskazna.ru/gisgmp/xsd/Common/2.0.1}EsiaUserInfoType" minOccurs="0"/>
 *         &lt;element ref="{http://roskazna.ru/gisgmp/xsd/SearchConditions/2.0.1}ChargesExportConditions"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "esiaUserInfo",
    "chargesExportConditions"
})
@XmlRootElement(name = "ExportChargesRequest", namespace = "urn://roskazna.ru/gisgmp/xsd/services/export-charges/2.0.1")
public class ExportChargesRequest
    extends ExportRequestType
{

    @XmlElement(name = "EsiaUserInfo", namespace = "urn://roskazna.ru/gisgmp/xsd/services/export-charges/2.0.1")
    protected EsiaUserInfoType esiaUserInfo;
    @XmlElement(name = "ChargesExportConditions", namespace = "http://roskazna.ru/gisgmp/xsd/SearchConditions/2.0.1", required = true)
    protected ChargesExportConditions chargesExportConditions;

    /**
     * Gets the value of the esiaUserInfo property.
     * 
     * @return
     *     possible object is
     *     {@link EsiaUserInfoType }
     *     
     */
    public EsiaUserInfoType getEsiaUserInfo() {
        return esiaUserInfo;
    }

    /**
     * Sets the value of the esiaUserInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EsiaUserInfoType }
     *     
     */
    public void setEsiaUserInfo(EsiaUserInfoType value) {
        this.esiaUserInfo = value;
    }

    /**
     * Условия для предоставления необходимой для уплаты информации
     * 
     * @return
     *     possible object is
     *     {@link ChargesExportConditions }
     *     
     */
    public ChargesExportConditions getChargesExportConditions() {
        return chargesExportConditions;
    }

    /**
     * Sets the value of the chargesExportConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargesExportConditions }
     *     
     */
    public void setChargesExportConditions(ChargesExportConditions value) {
        this.chargesExportConditions = value;
    }

}
