//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.18 at 06:29:50 PM MSK 
//


package com.skat.smev.gisgmp.model;

import com.skat.smev.gisgmp.model.AccountType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://roskazna.ru/gisgmp/xsd/Common/2.0.1}AccountType">
 *       &lt;sequence>
 *         &lt;element name="Bank" type="{http://roskazna.ru/gisgmp/xsd/Common/2.0.1}BankType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="accountNumber" use="required" type="{http://roskazna.ru/gisgmp/xsd/Common/2.0.1}AccountNumType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "OrgAccount")
public class OrgAccount
    extends AccountType
{


}
