//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.18 at 06:29:50 PM MSK 
//


package com.skat.smev.gisgmp.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UBPOrganizationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UBPOrganizationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://roskazna.ru/gisgmp/xsd/Organization/2.0.1}OrganizationType">
 *       &lt;attribute name="codeUBP" use="required" type="{http://roskazna.ru/gisgmp/xsd/Organization/2.0.1}kodUBPType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UBPOrganizationType", namespace = "http://roskazna.ru/gisgmp/xsd/Organization/2.0.1")
public class UBPOrganizationType
    extends OrganizationType
{

    @XmlAttribute(name = "codeUBP", required = true)
    protected String codeUBP;

    /**
     * Gets the value of the codeUBP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeUBP() {
        return codeUBP;
    }

    /**
     * Sets the value of the codeUBP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeUBP(String value) {
        this.codeUBP = value;
    }

}
