//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.18 at 06:29:50 PM MSK 
//


package com.skat.smev.gisgmp.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExportPaymentsKindType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExportPaymentsKindType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PAYMENT"/>
 *     &lt;enumeration value="PAYMENTMODIFIED"/>
 *     &lt;enumeration value="PAYMENTUNMATCHED"/>
 *     &lt;enumeration value="PAYMENTCANCELLED"/>
 *     &lt;enumeration value="PAYMENTMAINCHARGE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ExportPaymentsKindType", namespace = "http://roskazna.ru/gisgmp/xsd/SearchConditions/2.0.1")
@XmlEnum
public enum ExportPaymentsKindType {

    PAYMENT,
    PAYMENTMODIFIED,
    PAYMENTUNMATCHED,
    PAYMENTCANCELLED,
    PAYMENTMAINCHARGE;

    public String value() {
        return name();
    }

    public static ExportPaymentsKindType fromValue(String v) {
        return valueOf(v);
    }

}
