//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.18 at 06:29:50 PM MSK 
//


package com.skat.smev.gisgmp.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PayersConditionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PayersConditionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="PayerInn" type="{http://roskazna.ru/gisgmp/xsd/Common/2.0.1}INNType" maxOccurs="100"/>
 *           &lt;element name="PayerIdentifier" type="{http://roskazna.ru/gisgmp/xsd/Common/2.0.1}PayerIdentifierType" maxOccurs="100"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://roskazna.ru/gisgmp/xsd/Common/2.0.1}TimeInterval" minOccurs="0"/>
 *         &lt;element ref="{http://roskazna.ru/gisgmp/xsd/Common/2.0.1}KBKlist" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayersConditionsType", namespace = "http://roskazna.ru/gisgmp/xsd/SearchConditions/2.0.1", propOrder = {
    "payerInn",
    "payerIdentifier",
    "timeInterval",
    "kbKlist"
})
public class PayersConditionsType {

    @XmlElement(name = "PayerInn")
    protected List<String> payerInn;
    @XmlElement(name = "PayerIdentifier")
    protected List<String> payerIdentifier;
    @XmlElement(name = "TimeInterval", namespace = "http://roskazna.ru/gisgmp/xsd/Common/2.0.1")
    protected TimeIntervalType timeInterval;
    @XmlElement(name = "KBKlist", namespace = "http://roskazna.ru/gisgmp/xsd/Common/2.0.1")
    protected KBKlist kbKlist;

    /**
     * Gets the value of the payerInn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payerInn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayerInn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPayerInn() {
        if (payerInn == null) {
            payerInn = new ArrayList<String>();
        }
        return this.payerInn;
    }

    /**
     * Gets the value of the payerIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payerIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayerIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPayerIdentifier() {
        if (payerIdentifier == null) {
            payerIdentifier = new ArrayList<String>();
        }
        return this.payerIdentifier;
    }

    /**
     * Временной интервал, за который запрашивается информация из ГИС ГМП
     * 
     * @return
     *     possible object is
     *     {@link TimeIntervalType }
     *     
     */
    public TimeIntervalType getTimeInterval() {
        return timeInterval;
    }

    /**
     * Sets the value of the timeInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeIntervalType }
     *     
     */
    public void setTimeInterval(TimeIntervalType value) {
        this.timeInterval = value;
    }

    /**
     * Перечень КБК
     * 
     * @return
     *     possible object is
     *     {@link KBKlist }
     *     
     */
    public KBKlist getKBKlist() {
        return kbKlist;
    }

    /**
     * Sets the value of the kbKlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link KBKlist }
     *     
     */
    public void setKBKlist(KBKlist value) {
        this.kbKlist = value;
    }

}
